<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SAMSUNG Galaxy S21 FE 5G (Lavender, 128 GB)</name>
   <tag></tag>
   <elementGuidId>1eca240a-b2d7-45af-9f43-3c0e8ddea8b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._4rR01T</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ef34646-3857-4b20-9e60-041463c8709e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_4rR01T</value>
      <webElementGuid>2077f626-a272-4a53-9aac-5b9396609f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SAMSUNG Galaxy S21 FE 5G (Lavender, 128 GB)</value>
      <webElementGuid>912ebd16-86ba-4cde-a20c-ae81b23c5c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_36fx1h _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_13oc-S&quot;]/div[1]/div[@class=&quot;_2kHMtA&quot;]/a[@class=&quot;_1fQZEK&quot;]/div[@class=&quot;_3pLy-c row&quot;]/div[@class=&quot;col col-7-12&quot;]/div[@class=&quot;_4rR01T&quot;]</value>
      <webElementGuid>24b085af-f117-464d-ac4b-133c9455bd06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/a/div[2]/div/div</value>
      <webElementGuid>35840f93-47ec-4c66-8340-b942f46c017b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Compare'])[1]/following::div[5]</value>
      <webElementGuid>eba4aa75-9181-40df-8114-9456a2304f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newest First'])[1]/following::div[16]</value>
      <webElementGuid>0547eb03-44ae-450f-a7e3-5d3a182688ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&amp;'])[1]/preceding::div[2]</value>
      <webElementGuid>16a04522-5687-4f64-b21a-7194286f4d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹39,999'])[1]/preceding::div[4]</value>
      <webElementGuid>0fca50ea-23be-4dc2-bae0-7f6487088b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SAMSUNG Galaxy S21 FE 5G (Lavender, 128 GB)']/parent::*</value>
      <webElementGuid>32c10fdc-d603-4f07-bc00-406a56e338b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div/div</value>
      <webElementGuid>0021058e-d3ac-45c0-8005-954b6930ccf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SAMSUNG Galaxy S21 FE 5G (Lavender, 128 GB)' or . = 'SAMSUNG Galaxy S21 FE 5G (Lavender, 128 GB)')]</value>
      <webElementGuid>02eb8e01-ef91-4841-960d-23d66e8005b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
