<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RETRY</name>
   <tag></tag>
   <elementGuidId>b800dc21-629d-483e-a38c-f1ee12191151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._2KpZ6l.vm3SEU._3dESVI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div[3]/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d575e43-1d3c-477e-a30e-0145da69b6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2KpZ6l vm3SEU _3dESVI</value>
      <webElementGuid>4d719935-b06b-4c8b-85c9-f5ef0c5274ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RETRY</value>
      <webElementGuid>eef7776f-5534-40be-87f5-dc0ab56e2eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_36fx1h _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_3E8aIl _2qUd5H&quot;]/div[@class=&quot;ZVE96X&quot;]/div[1]/button[@class=&quot;_2KpZ6l vm3SEU _3dESVI&quot;]</value>
      <webElementGuid>616336a5-5bb4-439b-9c4e-840e77919397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div/button</value>
      <webElementGuid>5f6ecf25-4f47-4359-8c59-c991259858d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please try again'])[1]/following::button[1]</value>
      <webElementGuid>8d3c1823-0881-4577-bf2d-a7377dbcb49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Something', &quot;'&quot;, 's not right!')])[1]/following::button[1]</value>
      <webElementGuid>2e5f01a2-2400-43a3-95f7-bdb135b4dbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABOUT'])[1]/preceding::button[1]</value>
      <webElementGuid>72921e22-ba65-45e6-84c1-9f44b5801a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::button[1]</value>
      <webElementGuid>fe09a27e-b4fe-40bc-a6fe-4c1a88613ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RETRY']/parent::*</value>
      <webElementGuid>f580f6b1-ec3a-4152-867d-c937bf19c167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>090656ff-f886-48e4-beec-27eca39584a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'RETRY' or . = 'RETRY')]</value>
      <webElementGuid>60356cc0-a473-4cfa-b5cf-4bc9983ad795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
