<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Follow us_MuiBackdrop-root MuiBackdrop-_73e6c6</name>
   <tag></tag>
   <elementGuidId>9b63c446-2eab-4fc5-9679-eb2720a0187c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiPopover-root.MuiModal-root.css-x2f0qg > div.MuiBackdrop-root.MuiBackdrop-invisible.css-esi9ax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>894484d8-b1bc-4b9b-9516-886b647116ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ef9559b4-2e1d-418c-a3ba-cadc47a0ccdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBackdrop-root MuiBackdrop-invisible css-esi9ax</value>
      <webElementGuid>73ff0ecb-5c2a-4b42-ba0d-310dafd6d351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-body&quot;]/div[@class=&quot;MuiPopover-root MuiModal-root css-x2f0qg&quot;]/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-esi9ax&quot;]</value>
      <webElementGuid>dbc16c2f-99d9-4750-89aa-ea6e189da7b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>68de3f3a-4fe3-487f-82d2-8346e2d2a2e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
