<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mui-30</name>
   <tag></tag>
   <elementGuidId>78d3442b-2fe5-4b73-833a-529e633c830f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-30</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'Include consumer needs category' and @type = 'text' and @id = 'mui-30']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a422bca-b566-4844-a03e-3684392fd256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7cceebd5-12a3-4537-a71d-e6bf41cb5ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ad284686-4db5-4900-bf1d-cb1287de7b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Include consumer needs category</value>
      <webElementGuid>80936446-7f8a-407a-a1f2-5b918b0192e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cfaeb7b-5cd4-47b6-85f8-4e86cfbc3599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart MuiInputBase-inputAdornedEnd css-1j52k9r</value>
      <webElementGuid>65d3d742-7f97-4f95-b7f4-def7d46f669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-30</value>
      <webElementGuid>5829a89a-b9e9-4a54-aa1f-5dc8cb8dee3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-30&quot;)</value>
      <webElementGuid>97d36562-e9ca-4b62-aa05-294f766cae44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-30']</value>
      <webElementGuid>63925897-c17e-4a8b-ba10-9be5f5f19158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>97fae273-a39a-4b2b-b07c-9f2284dffb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>04516f41-0850-4c80-ae45-b4b28af15c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Include consumer needs category' and @type = 'text' and @id = 'mui-30']</value>
      <webElementGuid>09c69c0b-1f6c-4fe4-906d-7770bf0b5c39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
