<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mui-27</name>
   <tag></tag>
   <elementGuidId>a7e54c21-9b3a-4aaa-b352-c0d79e5c14c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'e.g. China' and @type = 'text' and @id = 'mui-27']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da710fb8-4b07-478f-a30b-00267a0a92f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec699061-9c69-4aeb-aa04-26c0cbf48a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c36f6800-d8aa-4e0d-9a5e-dc662847e714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. China</value>
      <webElementGuid>efc0162f-96fc-4a74-84e3-2d3e00b2c91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5bb18e1d-884e-4c40-b8be-70f3a3f38510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart MuiInputBase-inputAdornedEnd css-1j52k9r</value>
      <webElementGuid>4da8a8b5-ada2-4c1a-9aee-f2489ad53713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-27</value>
      <webElementGuid>7f2234bb-4200-4105-b739-e1f384267e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-27&quot;)</value>
      <webElementGuid>6381c208-7cfd-4844-b400-bca2b15cdc7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-27']</value>
      <webElementGuid>5c46fd39-9d8f-439d-80d3-4494f3fa453d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>130d7059-2c8e-4517-9d6b-9736f9c4060e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>d09fb0ad-e1c7-4658-ae79-7ec731c4a032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'e.g. China' and @type = 'text' and @id = 'mui-27']</value>
      <webElementGuid>714af7f2-642b-42be-a761-fd9dd77204b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
