<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_5_1</name>
   <tag></tag>
   <elementGuidId>964ad411-39b4-470c-a502-3f2cf68b58f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-41-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id = 'mui-41-option-0' and (text() = '&lt; 5%' or . = '&lt; 5%')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fa38793a-bd7c-451f-8ddd-43216709f28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d1a12ee5-f7ca-444f-a8aa-01457acbc82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5da8c85d-68bc-4b1e-8ea0-a8c74fb7cbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-41-option-0</value>
      <webElementGuid>fb74e852-c4aa-4105-8bee-2b4a463d5acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1802664f-2f6c-45d9-9dc4-da5e8c3af963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b57e6b5e-f100-4bb8-b9ce-7e24cc51cc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed620d00-1739-492d-8aef-1e74105cc5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>24f3ee89-315f-4d10-8895-6b10e8b49363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Less than 5%</value>
      <webElementGuid>c31106d3-48f7-434f-a50a-412eb9227020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt; 5%</value>
      <webElementGuid>95b46bc5-064e-4870-8f82-bc5031248aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-41-option-0&quot;)</value>
      <webElementGuid>ba9e85b0-edc2-4c2f-ac95-4e0d344f1d69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-41-option-0']</value>
      <webElementGuid>93215242-9ffc-487d-8fa5-061ffbed158a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-41-listbox']/li</value>
      <webElementGuid>c3f633bf-8197-4511-8901-062c0cb7852b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[14]/following::li[1]</value>
      <webElementGuid>3b6a13a1-935d-44c0-887f-11adec0a5318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[13]/following::li[1]</value>
      <webElementGuid>05ade78c-aa67-4cfd-87af-c443a42e4f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>= 5%'])[1]/preceding::li[1]</value>
      <webElementGuid>92a0b42c-d646-4b9b-92b2-dbea44a8fe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>= 10%'])[1]/preceding::li[2]</value>
      <webElementGuid>b251bd26-706b-47a0-9ffb-77c1c0fc6993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt; 5%']/parent::*</value>
      <webElementGuid>f7c56568-307f-4957-a571-3e2bf5867941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>b313afa2-9e90-42be-a459-dec4ac30a29c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-41-option-0' and (text() = '&lt; 5%' or . = '&lt; 5%')]</value>
      <webElementGuid>3cd06f0f-e727-416f-8e6b-a14970d2da5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
