<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Dairy</name>
   <tag></tag>
   <elementGuidId>24273607-28ad-40fc-a04c-0c8c0e14130c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-17-option-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mui-17-option-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1b13557b-2dec-4af2-bbd2-7c31af86c1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>92747c04-d2f8-4cf9-9a78-fd6c9e80ed95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>84b0bd6a-e49d-41c1-8125-b35855a32e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-17-option-2</value>
      <webElementGuid>51e1ff6e-f6e5-4be0-a44e-842f4d50288f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>49439389-416b-4912-b965-4a4a93c7e9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a07eaaa-3697-4e9a-8a80-3911955a2126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e548e563-d935-41d0-95e0-3e8a9cb8f1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>26d480c6-1ca1-4a4e-98f5-1f36a71faa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dairy</value>
      <webElementGuid>c424d7b3-7e6e-4eb4-9f0b-1f8764b7d27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-17-option-2&quot;)</value>
      <webElementGuid>c8ae53cb-4f9d-46ad-bf22-541e827018d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='mui-17-option-2']</value>
      <webElementGuid>a3a8d9c3-087b-4be0-bf66-3a92b40bc3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mui-17-listbox']/li[3]</value>
      <webElementGuid>1dd88564-54c9-475d-af0d-d84e29b60e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beverage'])[1]/following::li[1]</value>
      <webElementGuid>107cafa6-4e3f-4ab0-bb5e-bd4d2048a7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Plant-based'])[1]/following::li[2]</value>
      <webElementGuid>b1d4b803-6357-4e00-92c7-b5f15914d2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ready-to-Eat'])[1]/preceding::li[1]</value>
      <webElementGuid>1b254566-b3c2-4025-89db-f2db3943cfb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Snacks'])[1]/preceding::li[2]</value>
      <webElementGuid>03fe6881-9e2b-4f5e-a9c2-d55db2c03311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dairy']/parent::*</value>
      <webElementGuid>c6a686c2-4938-4c95-a6f6-db8301dcf1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>632e95c4-a5c3-4636-a9a9-a6c0cd7483d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'mui-17-option-2' and (text() = 'Dairy' or . = 'Dairy')]</value>
      <webElementGuid>ead1c0d5-1b42-4151-bb23-d58224b2e6d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
