<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Canada</name>
   <tag></tag>
   <elementGuidId>2c8e354f-d862-4311-9e3c-cd630365e0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-19-option-3 > span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-1w2zoug</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='mui-19-option-3']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>835de9d3-a542-4bb5-b4bf-09e417172a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label css-1w2zoug</value>
      <webElementGuid>f7d7f6fc-fe7d-46f7-a848-ec4fd5b50f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Canada</value>
      <webElementGuid>fbf4d8e8-e632-410e-bf79-398aec582499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-19-option-3&quot;)/span[@class=&quot;MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label css-1w2zoug&quot;]</value>
      <webElementGuid>871ef0ea-6e92-48cd-b54f-8c241c60dfc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='mui-19-option-3']/span[2]</value>
      <webElementGuid>8589b097-ec75-469a-8ad1-2108102f815d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brazil'])[1]/following::span[2]</value>
      <webElementGuid>5187a779-7936-4e7a-93bc-3e3b3b8676e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australia'])[1]/following::span[4]</value>
      <webElementGuid>b8548240-a048-463f-a470-58b558ec6c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='China'])[1]/preceding::span[2]</value>
      <webElementGuid>f74eace2-98d4-4126-af74-af653b983904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colombia'])[1]/preceding::span[4]</value>
      <webElementGuid>574c7329-5a52-4e95-a4c1-0895d8bd3954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Canada']/parent::*</value>
      <webElementGuid>ca8e427b-ad56-4821-8a81-62960268b307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]/span[2]</value>
      <webElementGuid>bef81b2b-1ed5-421a-b0e5-b5c57a0a81bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Canada' or . = 'Canada')]</value>
      <webElementGuid>6be7e003-d388-41ca-b1be-4581f7449681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
