<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Australia</name>
   <tag></tag>
   <elementGuidId>fc28f53e-41cb-448f-b6da-7cff28b0b230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-19-option-1 > span.MuiTypography-root.MuiTypography-body1.MuiFormControlLabel-label.css-1w2zoug</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='mui-19-option-1']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>650aacb5-bef6-4831-8d6f-79627fd51657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label css-1w2zoug</value>
      <webElementGuid>00073bf4-3b60-439f-9680-b9afc75af635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Australia</value>
      <webElementGuid>ac56e71e-6147-4f41-b49e-b77a4e2e66d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-19-option-1&quot;)/span[@class=&quot;MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label css-1w2zoug&quot;]</value>
      <webElementGuid>9eea8a79-1975-4011-ae6b-1b9ca054c3ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='mui-19-option-1']/span[2]</value>
      <webElementGuid>f260578f-a97b-44a3-8138-3372e1fb84ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asia'])[1]/following::span[2]</value>
      <webElementGuid>4381296a-69fb-45e8-9b55-71725afe9b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow us:'])[1]/following::span[4]</value>
      <webElementGuid>047cdbd1-0ec2-4fe4-aaa5-ed1581d1577c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brazil'])[1]/preceding::span[2]</value>
      <webElementGuid>e2275852-d9df-46ca-a052-66ca2524bb04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canada'])[1]/preceding::span[4]</value>
      <webElementGuid>5c0a79f5-f586-403a-a5be-40a39156f8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Australia']/parent::*</value>
      <webElementGuid>0e61a1e5-c53f-4f22-8c1d-e4cde199fe6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span[2]</value>
      <webElementGuid>f6a566f0-9436-4eda-b30b-1e13bd9272dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Australia' or . = 'Australia')]</value>
      <webElementGuid>775cae99-0636-4921-81a2-e55b29a40115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
