<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pillar Name_PillarName</name>
   <tag></tag>
   <elementGuidId>fc3051c4-907f-4c23-9f34-a5576ffbc192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'PillarName' and @placeholder = 'e.g. Taste' and @type = 'text' and @id = 'mui-20']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mui-20</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>caa7c1e2-5d88-4ecb-8e5a-16b6d6238995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fbb6af2f-1003-4a94-8c26-b3bf12da86fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PillarName</value>
      <webElementGuid>34d3954b-d4af-4729-bbba-f70e912a2ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. Taste</value>
      <webElementGuid>d8ee9f57-d4b0-4552-b674-1f1946b44612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6ed4fc7-76ef-41d1-8c68-593eec07e231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-v6iu6c</value>
      <webElementGuid>d46df64c-79d3-4172-b316-796ecaf5ad63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-20</value>
      <webElementGuid>01eb828a-7af0-4757-b19f-e639d2ddc4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-20&quot;)</value>
      <webElementGuid>2c3c3a61-a27c-4773-ab6d-0e6f456a248f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-20']</value>
      <webElementGuid>32856ee5-b866-4bc9-a2d2-be571a83a6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='simple-tabpanel-0']/div/form/div/div/div/input</value>
      <webElementGuid>28f69b85-b9db-479e-a528-b09ae092f2cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>04c9f2df-87b8-4813-a16a-60121f1dcb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'PillarName' and @placeholder = 'e.g. Taste' and @type = 'text' and @id = 'mui-20']</value>
      <webElementGuid>79a339ce-5fa3-4585-8b66-a9039d0578b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
