<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Agar Agar</name>
   <tag></tag>
   <elementGuidId>ac5e5199-cd22-43ec-83ee-1de016aa4b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.MuiFormControlLabel-root.MuiFormControlLabel-labelPlacementEnd.css-x2ng6j</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div[3]/div/div/div/div[4]/fieldset/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8e1b6e74-3546-4966-a931-5ac0e972bb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-x2ng6j</value>
      <webElementGuid>944a6b55-f40c-446b-9ed5-47be87c1c561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agar Agar</value>
      <webElementGuid>4276276b-f151-4919-82a0-7031c185aa82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;MuiBox-root css-1ondsk&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl css-1ekb41w&quot;]/div[@class=&quot;MuiBox-root css-j7qwjs&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-pp7nsx&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-8snq7r&quot;]/div[@class=&quot;checkBoxList&quot;]/div[1]/div[4]/fieldset[@class=&quot;MuiFormControl-root css-s7unyp&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/div[@class=&quot;MuiFormGroup-root MuiFormGroup-row css-p58oka&quot;]/label[@class=&quot;MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-x2ng6j&quot;]</value>
      <webElementGuid>847f3e7b-17a3-4570-a035-ce9be34bca00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div[3]/div/div/div/div[4]/fieldset/div/div/label</value>
      <webElementGuid>872ff64b-3fd5-4c12-9f00-45c6e629d205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adzuki Bean'])[2]/following::label[1]</value>
      <webElementGuid>d3dd3901-06b0-4b93-b11e-2850a0a53ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acerola'])[2]/following::label[2]</value>
      <webElementGuid>f90e8783-ab5d-459b-ac19-7dcb4c9d9714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agarwood'])[1]/preceding::label[1]</value>
      <webElementGuid>fd60a96e-337e-4619-81b3-bf41a9330be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/div/label</value>
      <webElementGuid>97752a6c-936e-4dd8-915a-946f6c5e3601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Agar Agar' or . = 'Agar Agar')]</value>
      <webElementGuid>cbf102eb-bdab-4e88-9df7-1cba4e41785b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
