<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BUY NOW</name>
   <tag></tag>
   <elementGuidId>9ebdba76-cfe2-4ca8-a2b4-5766a4a71a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._2KpZ6l._2U9uOA.ihZ75k._3AWRsL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b05de7fa-4e75-4ad0-950b-d9346f0266ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2KpZ6l _2U9uOA ihZ75k _3AWRsL</value>
      <webElementGuid>becbe1b7-61cb-4815-9021-14e50366fa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e900562-c853-4a31-964e-37a873eeea4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> BUY NOW</value>
      <webElementGuid>40457488-7a35-45b2-afbd-10836a434ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;_2c7YLP UtUXW0 _6t1WkM _3HqJxg&quot;]/div[@class=&quot;_1YokD2 _2GoDe3&quot;]/div[@class=&quot;_1YokD2 _3Mn1Gg col-5-12 _78xt5Y&quot;]/div[@class=&quot;_1AtVbE col-12-12&quot;]/div[@class=&quot;_1p3MFP dTTu2M&quot;]/ul[@class=&quot;row&quot;]/li[@class=&quot;col col-6-12&quot;]/form[1]/button[@class=&quot;_2KpZ6l _2U9uOA ihZ75k _3AWRsL&quot;]</value>
      <webElementGuid>cfe466ff-7510-4abb-a84f-c6a4ba69bdd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>47d81e01-9645-4aa1-9564-a106246d41f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div[3]/div/div/div[2]/div/ul/li[2]/form/button</value>
      <webElementGuid>7bcadcaf-c8c5-4f81-bcbf-7dda2a27de74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Offer Zone'])[1]/following::button[2]</value>
      <webElementGuid>efe793eb-bccc-4da5-bb88-05dd598f2388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::button[1]</value>
      <webElementGuid>2547d925-9fb9-46d3-9b60-27535ffe3059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobiles &amp; Accessories'])[1]/preceding::button[1]</value>
      <webElementGuid>ec8a4fc3-e4c0-49d4-ba05-3b170ffee682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BUY NOW']/parent::*</value>
      <webElementGuid>bf9de42c-d041-47a5-b0c1-5dc2893c0e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>d7f80da2-f68b-4182-bd93-0ba8e8fb9d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' BUY NOW' or . = ' BUY NOW')]</value>
      <webElementGuid>3372f635-3ffb-4907-a80e-8fe076dccf7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
