<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Abalone</name>
   <tag></tag>
   <elementGuidId>f3c2943a-b373-45af-acc0-094d7dc3baef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bucket-search-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='bucket-search-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d6b2a889-6a95-46a8-b1ff-175024c553e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f66d2fbe-4efe-4342-ae77-ef5303aa49b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>51c38067-3789-4515-ad70-477c8b25e025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bucket-search-option-0</value>
      <webElementGuid>7cb1eb55-4508-4436-9b40-b219e71c40d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9991ac5a-fbc0-4dd4-be86-9fb03593e6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d2b129b5-d580-4169-9beb-52fb09915e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c75748ae-130c-44a7-ad60-91118072ca36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>2d1aeb6e-7729-4d7f-9b43-d4d064556692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Abalone</value>
      <webElementGuid>51b2849b-052e-4ab1-8c47-244bc388d11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bucket-search-option-0&quot;)</value>
      <webElementGuid>fe8ffc33-8b0e-405f-ad19-f1874af69bfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='bucket-search-option-0']</value>
      <webElementGuid>96405f2c-0f0e-4277-a064-21061dde7ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bucket-search-listbox']/li/ul/li</value>
      <webElementGuid>55b81e52-3844-4930-8890-f6e4b74021d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingredient'])[1]/following::li[1]</value>
      <webElementGuid>5ddacf19-ce28-4c37-8a85-6285218ae5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'bucket-search-option-0', '&quot;', ')')])[1]/following::li[4]</value>
      <webElementGuid>80c17804-127a-409e-bce9-225cc7fe6842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acacia'])[1]/preceding::li[1]</value>
      <webElementGuid>947e80ca-157f-4c0d-bc92-3396c1af6242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acai'])[1]/preceding::li[2]</value>
      <webElementGuid>d104917d-3911-4f3f-8e2b-167821fe164e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Abalone']/parent::*</value>
      <webElementGuid>d051d7c8-6608-4845-9ce1-8d16c9d405e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li</value>
      <webElementGuid>103f8c7f-448a-47ce-8812-c3f9b3848f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'bucket-search-option-0' and (text() = 'Abalone' or . = 'Abalone')]</value>
      <webElementGuid>46eb21f4-8b00-4f3f-9189-f0ee8ccbfd99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
