<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Chocolatey</name>
   <tag></tag>
   <elementGuidId>243f4028-4572-4e1b-afd9-6905d3a7c4ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bucket-search-option-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='bucket-search-option-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b00b1d1b-e0eb-4a92-b2fe-872aaf0fbf74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>13d32269-5e24-423f-8fa9-081e3c5d162d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>fd54eb01-dede-4a39-9257-d93cdc50e30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bucket-search-option-8</value>
      <webElementGuid>75d4c851-9b60-4a0c-8f50-c461c146be8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>af5ef175-f5ee-4149-8996-ad0e08979440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>77088d84-e3d2-4067-a3a8-bb23c043ef41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f22cddea-ff40-4ec8-bdde-71af04dedfc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>d4d95847-336d-48fb-bf77-a59efc227e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chocolatey</value>
      <webElementGuid>f9bc1661-e95e-420a-af32-6d111e72e072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bucket-search-option-8&quot;)</value>
      <webElementGuid>9864b17e-cd9f-4b52-bedd-118c9c99100d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='bucket-search-option-8']</value>
      <webElementGuid>1b6e6e63-17e0-4a6f-be5b-15f77cce50c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='bucket-search-listbox']/li[2]/ul/li</value>
      <webElementGuid>f394c785-5836-4b93-b284-eb22a58386ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theme'])[1]/following::li[1]</value>
      <webElementGuid>4d115abe-26d9-4c32-9375-5c84b404fbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='White Chocolate'])[1]/following::li[2]</value>
      <webElementGuid>6a81766c-9db2-4109-9894-24d8dbb2de36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chocolatey']/parent::*</value>
      <webElementGuid>96ae3b5e-9c9f-488c-af43-4284d713181e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li</value>
      <webElementGuid>c8ad9c7b-e23a-453d-b459-e62dfed8ccfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'bucket-search-option-8' and (text() = 'Chocolatey' or . = 'Chocolatey')]</value>
      <webElementGuid>9f75c020-3221-4587-8efb-c1e816e84ae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
