<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mui-18</name>
   <tag></tag>
   <elementGuidId>c139d710-6fb7-4cf3-8e55-5ea4b2a456cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mui-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mui-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e80d6748-c1eb-4c53-9667-b9bb4d061022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9276148-fbcf-4c38-8435-cab763ff786d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4d60697f-64a3-48d6-bf96-e63ccec1e901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Include consumer needs category</value>
      <webElementGuid>00575b17-790d-4c3d-9d59-b99bc4cd03a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e70d23b-824d-4f3a-b5c9-5e2ff7b9b132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedStart MuiInputBase-inputAdornedEnd css-1j52k9r</value>
      <webElementGuid>c873e9c8-6f6c-4ae1-b94f-fb4fdcbb250b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mui-18</value>
      <webElementGuid>39d0271c-56eb-4400-b179-366427f67600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mui-18&quot;)</value>
      <webElementGuid>3e473d30-eed0-4c26-bb18-c3d11ba52b74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mui-18']</value>
      <webElementGuid>42d4c9e4-5377-4d34-b4de-420e5515d3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>e9738ca8-095e-4331-81f9-de5a7f82cb3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>7b60cb44-461e-4ff1-9024-c792f19b4ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Include consumer needs category' and @type = 'text' and @id = 'mui-18']</value>
      <webElementGuid>ef101686-a722-4dee-a3d4-8726ae5b9135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
