<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUE</name>
   <tag></tag>
   <elementGuidId>ee149da9-82a7-4859-94a1-a63e3e65d118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button._2KpZ6l._1seccl._3AWRsL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='to-payment']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66954222-0d66-487f-a205-bdf56a1d3f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2KpZ6l _1seccl _3AWRsL</value>
      <webElementGuid>b7da57bf-6e11-4a32-92fb-4531fc6f6a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUE</value>
      <webElementGuid>f2a90150-aed5-40ee-9faf-792c6f0e930e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;to-payment&quot;)/button[@class=&quot;_2KpZ6l _1seccl _3AWRsL&quot;]</value>
      <webElementGuid>12ac3060-c938-46f5-baa6-d15517dff33f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='to-payment']/button</value>
      <webElementGuid>5ae7694b-35f3-4bf9-a3ac-78a7f46f4e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order confirmation email will be sent to'])[1]/following::button[1]</value>
      <webElementGuid>90d62c64-2d66-4b4a-8d03-a04139cecb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use GST Invoice'])[1]/following::button[1]</value>
      <webElementGuid>22628e58-b6a7-4485-ada6-b109d1f5e419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Options'])[1]/preceding::button[1]</value>
      <webElementGuid>419b1a94-e1cc-4fcc-9bf3-a4bd5474b8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Price details'])[1]/preceding::button[1]</value>
      <webElementGuid>326d636c-e5f8-402f-9d25-89dd0754f142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUE']/parent::*</value>
      <webElementGuid>30a38a8e-f1de-4733-a3e8-f2779397c0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button</value>
      <webElementGuid>c24df2d3-740a-4e52-a3c6-adc75149983e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CONTINUE' or . = 'CONTINUE')]</value>
      <webElementGuid>32ceefdb-dc4e-4fb0-b7d7-cee7141b06de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
